### PR TITLE
Merge HRM V1.14-rc into master

### PR DESCRIPTION
**Pull request by nickhurlburt**
A small fix for the KHP data pull.

### CODE REVIEW

**Comment by nickhurlburt** [comment]
@stephenhand do you know if this merge into master is necessary? Looks like there are conflicts.

**Comment by stephenhand** [comment]
No - this change backed out 'half working' changes in HRM at the time the RC branch was cut, but they are fully working on master now to the backout changes don't need to be merged.

I would suggest doing a 'non merge' where we merge the commits but don't actually apply any of the changes. Otherwise there will be unmerged commits hanging around on the RC branch forever that will confuse folks in the future - and this PR will keep coming backl from the dead :-/

**Comment by nickhurlburt** [comment]
I get what you're saying about not wanting unmerged commits lying around, though I'm not sure how to "merge the commits but don't actually apply any of the changes." -- help?

**Comment by stephenhand** [comment]
When you merge just take all the changes from master when resolving conflicts should do it

**Comment by nickhurlburt** [comment]
@stephenhand please take a look (should take 15 seconds). I must have mis-resolved the conflict because it wanted to undo what's on master, but then I manually changed it so there are no diffs. What you expected?

**Pull request merged**
