### PR TITLE
CHI-1594: Replace batches for streams in reindex endpoint.

### PR DESCRIPTION
**Pull request by stephenhand**
## Description

Demonstrates how to use node streams & pg-query-stream as a more efficient alternative to pulling large amounts of resources from the DB in multiple queries using LIMIT & OFFSET. 

This approach uses a single query under the hood, and node stream's built in buffering & flow control to manage how many resources can be in the service's memory at any given time

The stream APIs are a bit 'old school' and not very promise friendly. Node 19 & 20 leverage async iterators & generators to allow for much more functional and promise friendly APIs, so we could look at using those in the future

Assigning to @GPaoloni because I know he likes stuff like this :-)

### CODE REVIEW

**Review by GPaoloni — APPROVED** [review]
The code makes perfect sense to me! Gotta get more used to this API for sure

I have a question tho, this stream is acting on the DB but for the http response the query's result must be in server's memory at some point, right? Or I'm missing something here?

**Comment by stephenhand** [comment]
> The code makes perfect sense to me! Gotta get more used to this API for sure
> 
> I have a question tho, this stream is acting on the DB but for the http response the query's result must be in server's memory at some point, right? Or I'm missing something here?

Correct, for not the response is built up in memory. The response only contains resource IDs or a maximum of 50 errors though, so shouldn't be a problem even reindexing the entire KHP dataset

We could stream the response out in future but there's a couple of considerations:

* JSON isn't a very 'streaming friendly' format, because it expects opening and closing delimiters, anything reading it on the other side doesn't consider the information 'complete' until it gets that closing delimiter. Something like CSV or JSONL is better because each item can be processed as it comes off the wire (without hacking deserialisers)
* You have to be careful streaming all the way through from the DB to a HTTP response. By doing this, you allow the HTTP client to control the lifetime of your database cursor with how long it takes to read the response. If it takes a long time to read your response, it can hold that database cursor and any associated locks open for a long time, which is undesirable. The technique can still be used but you have to have safeguards like timeouts and appropriately sized buffering to protect the DB

For these reasons I thought it was simpler to buffer up the whole response in memory and send it as normal for this implementation

**Review by robert-bo-davis — APPROVED** [review]
This is a cool pattern for the tool belt... but it feels like overkill for the amounts of data we are actually dealing with.

I'm not positive that the price we pay in cognitive load/complexity addition really balances out the performance benefit. In my experience LIMIT/OFFSET performance doesn't get really hairy until you are tens of thousands of pages (and many gigabytes) deep. I'm not against it, but it feels like one of those things that is academically correct, but maybe comes at a price of complexity and a departure from the "simple" patterns that most devs are accustomed to.

Not a blocker, just my thoughts.

**Comment by stephenhand** [comment]
@robert-bo-davis This was done more as a demo of a pattern than anything - totally agree it's not required to optimise this endpoint.

My thoughts in favour of merging it was thus: precisely because it is a bit of low priority, peripheral maintenance code, it might be a good place to show this kind of pattern being used with a real use case.

It would allow the team some exposure to the pattern without it being a critical path thing that you absolutely have to understand to work with the core business logic of the system, then should we ever need to use the pattern to address a real problem, there would be some existing familiarity and working example code to work off - as opposed to a dusty old unmerged PR that hardly anyone looked at in the first place and those that did forgot about.

It was slightly inspired by our 'internal tools are a good place to try out new stuff' convo 

But your points are valid as well, and whilst it is 'internal tooling' it is also an endpoint in a production service, so maybe not the place to freestyle...~

We don't have to merge it, I'm good either way.

**Comment by robert-bo-davis** [comment]
That totally makes sense to me! I think we are on the same page (as usual), just wanted to make sure the long-term thinking was happening out loud. ;)

I'm good to merge it!

**Pull request merged**
