### PR TITLE
chore: Add all profile related operations to Audits table [CHI-2318]

### PR DESCRIPTION
**Pull request by mythilytm**
## Description
This PR adds audit triggers to the profiles related tables.

### Checklist
- [x] [Corresponding issue has been opened](https://tech-matters.atlassian.net/browse/CHI-2602)
- [x] New tests added

### Verification steps
Service tests :)

### CODE REVIEW

**Comment by GPaoloni** [comment]
@mythilytm this PR should be ready. FYI in case you want to review my changes.

**Review by mythilytm — COMMENTED** [review]
Thanks Gian. This looks great. Good idea to the record type. Some of the issues were partly because of this in retrospect.

**Review by stephenhand — APPROVED** [review]
LGTM, thx for the comprehensive tests!

In future we might look at strategies to DRY up the tests a little, using jest `each` or helper functions to take the repetition out of specifying expectations, but this is great for now

**Comment by GPaoloni** [comment]
> In future we might look at strategies to DRY up the tests a little, using jest each or helper functions to take the repetition out of specifying expectations, but this is great for now

This makes absolute sense to me, but abstracting the "before", "test" and "after" behavior might take a while here :P Happy to tackle this ugly debt. https://tech-matters.atlassian.net/browse/CHI-2618

**Pull request merged**
