### PR TITLE
Adding PL permissions

### PR DESCRIPTION
**Pull request by janorivera**
## Description
@GPaoloni  I've decided to just create the pl permissions since I have to create them in the future  anyway.

### CODE REVIEW

**Review by stephenhand — APPROVED** [review]
LGTM

**Comment by GPaoloni** [comment]
@janorivera While we have the endpoint to serve the permissions to the frontend, it is not really being consumed yet. Is an analogous piece to this in Flex too?

**Comment by janorivera** [comment]
@GPaoloni  you are right! there isn't a permission file in Flex. What is the best path moving forward? My thinking behind this PR was not to touch again something that seems very delicate (staging.env) and take the opportunity to do something in advance.
Can I just create the file in the Flex repo or should I revert the changes, I'm happy either way.
Out of curiosity, why don't we create these permissions for each helpline with the default settings as part of the deployment? Wouldn't that way be easier later on just to update the permissions file ? And is it not possible to consolidate these 2 files someway?

**Comment by GPaoloni** [comment]
> you are right! there isn't a permission file in Flex. What is the best path moving forward? 

In order for Flex to behave as expected, the same permissions file should be present there. This will be changed in the short term (hopefully), so Flex will "fetch the permissions rules on initialization". So yes, you should also bundle this in Flex for now. No need to revert this, this PR is correct!

> Out of curiosity, why don't we create these permissions for each helpline with the default settings as part of the deployment? Wouldn't that way be easier later on just to update the permissions file ? And is it not possible to consolidate these 2 files someway?

We thought it was not worth. When we have the actual specs, we need to re-deploy with the updated version anyways, so to simplify the workflow of setting up a new account we just go with `demo`. Happy to revisit this if you think otherwise!

> And is it not possible to consolidate these 2 files someway?

You mean the permissions files in HRM and in Flex? Everything is mostly setup for that, that's my goal as it will be much easier, but other things keep pushing that task. You could push from your side to go and finish that? ;P

**Pull request merged**
