### PR TITLE
CHI-1383 working transcripts

### PR DESCRIPTION
**Pull request by robert-bo-davis**
Primary Reviewer: @GPaoloni 

## Description
This is tested working transcripts in the development environment and local dev. It has sibling PRs in techmatters/flex-plugins#1009 and techmatters/serverless#349 for local dev.

It requires the sibling PR techmatters/infrastructure-config#85 to work in development. The TF changes in that PR have already been applied.

#260 should be merged after this

### Checklist
- [ ] Verified on desktop

### Related Issues
CHI-1383

### CODE REVIEW

**Comment by robert-bo-davis** [comment]
To get this to work in the development environment, I manually added the following SSM parameters:

/development/twilio/ACd8a2e89748318adf6ddff7df6948deaf/auth_token
/development/s3/ACd8a2e89748318adf6ddff7df6948deaf/docs_bucket_name

**Comment by robert-bo-davis** [comment]
A question that I'm not sure has been addressed yet is how we are going to deal with locking in the long running pollers running in multiple HRM instances. In the current design, race conditions could cause contact jobs to be sent to sqs twice and they could also cause completed jobs to be processed twice. The likelihood is low because of our relatively high timeout between polls, but it still exists.

**Review by stephenhand — APPROVED** [review]
LGTM

**Comment by robert-bo-davis** [comment]
> how we are going to deal with locking in the long running pollers running in multiple HRM instances.

I would suggest that we move to a version of the "hybrid-monolith" while we still have the long running loops. It would be fairly simple to strip this block out of `createService()` and into its own bin with an `npm start:contact-job-processor` script:

```javascript
  if (enableProcessContactJobs) {
    const processorIntervalId = processContactJobs();

    const gracefulExit = () => {
      clearInterval(processorIntervalId);
    };

    app.on('close', gracefulExit);
    // @ts-ignore
    app.close = () => {
      app.emit('close');
    };
  }
```

We could then add an additional service definition to the ECS cluster config that runs a single container that only runs that loop. This would keep the main "service" tasks pure http request/response and allow us to only run one container that handles the loop. This would eliminate the need for any locking. Well, reduce really since during deployment, multiple "job-processor" containers would be running for some amount of time.

If ECS scheduled tasks allowed more fine grained scheduling that once per minute I would suggest we use scheduled tasks for this, but since the lowest interval is one minute, and fargate billing rounds up to the nearest minute, there is no good reason for the extra complication that I can think of.

**Comment by stephenhand** [comment]
> 



> > how we are going to deal with locking in the long running pollers running in multiple HRM instances.
> 
> I would suggest that we move to a version of the "hybrid-monolith" while we still have the long running loops. It would be fairly simple to strip this block out of `createService()` and into its own bin with an `npm start:contact-job-processor` script:
> 
> ```js
>   if (enableProcessContactJobs) {
>     const processorIntervalId = processContactJobs();
> 
>     const gracefulExit = () => {
>       clearInterval(processorIntervalId);
>     };
> 
>     app.on('close', gracefulExit);
>     // @ts-ignore
>     app.close = () => {
>       app.emit('close');
>     };
>   }
> ```
> 
> We could then add an additional service definition to the ECS cluster config that runs a single container that only runs that loop. This would keep the main "service" tasks pure http request/response and allow us to only run one container that handles the loop. This would eliminate the need for any locking. Well, reduce really since during deployment multiple "job-processor" containers would be running for some amount of time.
> 
> If ECS scheduled tasks allowed more fine grained scheduling that once per minute I would suggest we use scheduled tasks for this, but since the lowest interval is one minute, and fargate billing rounds up to the nearest minute, there is no good reason for the extra complication that I can think of.

We can do as you suggest. My thought was always to manage concurrency via database locks, given the table shouldn't be highly contended. Or we could use an optimistic locking approach although again, since the table is unlikely to get so heavily contended it probably wouldn't be worth it.

It might be worth ensuring we have a robustish concurrency strategy even if we only use a single worker, just in case things go wrong and we end up with multiple job processors running simultaneously unexpectedly. Unless it's a huge amount more effort.

Of course, we are also trying to make our jobs idempotent as well, so then we're triple sure... :-P

**Review by GPaoloni — APPROVED** [review]

**Pull request merged**
